# Generated by Django 5.1.5 on 2025-04-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
